image:
  file: Dockerfile

tasks:
  - init: docker build -t docker.pkg.github.com/USERNAME/REPOSITORY/node-app:v1 . && docker push docker.pkg.github.com/USERNAME/REPOSITORY/node-app:v1
  - init: docker build -t docker.pkg.github.com/USERNAME/REPOSITORY/python-app:v1 . && docker push docker.pkg.github.com/USERNAME/REPOSITORY/python-app:v1
