name: ci
on:
  push:
    branches: main
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        uses: docker/login-action@v3
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/DenchikX/index:v1/DenchikX/dekbr
      - run: docker push ghcr.io/DenchikX/index:v1/DenchikX/dekbr
      - run: docker build -t github.com/denchikx/dekbr/main:v1
      - run: docker push github.com/denchikx/dekbr/main:v1
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 532075779
          token: 5942378382:AAEzEru5YxurKawezrIquBDCKOB7mjcm4qc
          message: ${{github.actor }}
      
